- name: Install TLS cert
  copy:
    dest: "{{ es_ssl_cert_path }}"
    content: "{{ es_ssl_cert_content }}"
    mode: 0644
    owner: 'root'
    group: 'elasticsearch'

- name: Install TLS key
  copy:
    dest: "{{ es_ssl_key_path }}"
    content: "{{ es_ssl_key_content }}"
    mode: 0640
    owner: 'root'
    group: 'elasticsearch'
